[package]
name = "microsandbox-db"
description = "Shared database entity definitions and connection helpers for the microsandbox project."
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "microsandbox_db"
path = "lib/lib.rs"

[dependencies]
async-trait = "0.1"
chrono.workspace = true
libsql = { version = "0.9", default-features = false, features = ["remote", "tls"] }
sea-orm = { workspace = true, features = ["proxy"] }
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
microsandbox-migration = { path = "../migration" }
tempfile.workspace = true
